name: Update Publications

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - '.github/scripts/**'

jobs:
  update-publications:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt

    - name: Fetch new publications
      env:
        ENTREZ_EMAIL: ${{ secrets.ENTREZ_EMAIL }}
      run: python .github/scripts/fetch_pub.py > new_dois.txt

    - name: Check for new DOIs
      id: filter_dois
      run: |
        if [ -s new_dois.txt ]; then
          count=$(wc -l < new_dois.txt)
          echo "new_dois=true" >> $GITHUB_OUTPUT
          echo "new_count=$count" >> $GITHUB_OUTPUT
        else
          echo "new_dois=false" >> $GITHUB_OUTPUT
          echo "new_count=0" >> $GITHUB_OUTPUT
        fi

    - name: Process publications
      if: github.event_name == 'workflow_dispatch' || steps.filter_dois.outputs.new_dois == 'true'
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          python .github/scripts/add_pub.py --force
        else
          python .github/scripts/add_pub.py --dois-file new_dois.txt
        fi

    - name: Check for changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .

        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          git commit -m "Update all publications"
        else
          git commit -m "Add ${{ steps.filter_dois.outputs.new_count }} new publications"
        fi

        git push
